### ISSUE TITLE
How do you setup for Web Interface?

### ISSUE THREAD

**Issue by RogueIMP** [Mrjohns42/DALEK#1]
Your description says it can interact with a Web Interface.  Can you give some instructions on how to set that up? 
I'm building a Pi Tank, and want to attach this to the Web Interface that it uses.  I currently am using WebIOPi for the Tank controls.  Is it possible to incorporate this into that?

**Comment by Mrjohns42** [comment]
A friend wrote a little Java server and web app that handled the video feed and passed the web UI controls through to my script.  We had it all running on a little embedded linux board.

**Comment by Mrjohns42** [comment]
FOUND IT!
https://github.com/MasterPpv/ENG-198-Project

**Comment by RogueIMP** [comment]
Sweet, Thanks!
